# DVC Pipeline for Debt Collection ML
# Repository: avirup112/Demo-Banking

stages:
  data_generation:
    cmd: python src/data/data_generator.py --output data/raw/synthetic_debt_data.csv --size 10000
    deps:
    - src/data/data_generator.py
    outs:
    - data/raw/synthetic_debt_data.csv
    
  data_preprocessing:
    cmd: python src/data/data_preprocessor.py --input data/raw/synthetic_debt_data.csv --output data/processed/
    deps:
    - src/data/data_preprocessor.py
    - data/raw/synthetic_debt_data.csv
    outs:
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    - data/processed/y_train.npy
    - data/processed/y_test.npy
    
  feature_engineering:
    cmd: python src/features/feature_engineering.py --input data/processed/ --output data/features/
    deps:
    - src/features/feature_engineering.py
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    outs:
    - data/features/X_train_features.npy
    - data/features/X_test_features.npy
    
  model_training:
    cmd: python run_complete_pipeline.py --dagshub-owner avirup112 --dagshub-repo Demo-Banking
    deps:
    - run_complete_pipeline.py
    - data/features/X_train_features.npy
    - data/features/X_test_features.npy
    - data/processed/y_train.npy
    - data/processed/y_test.npy
    outs:
    - models/trained/best_model.joblib
    - reports/results_summary.json
    metrics:
    - reports/metrics.json